training_type: ['cogvideox_text_to_video_sft', 'cogvideox_image_to_video_sft']
accelerate_config: 'uncompiled_1.yaml'
gpu_ids: '0'
pretrained_model_name-or_path: ''
data_root: ''
caption_column: 'prompt.txt'
video_column: 'videos.txt'
id_token: 'LORA_NAME'
height_buckets: 720
width_buckets: 480
frame_buckets: 32
dataloader_num_workers: 6
pin_memory: true
validation_prompt: ''
validation_prompt_separator: ':::'
num_validation_videos: 0
validation_epochs: 0
seed: 42
rank: 128
lora_alpha: 128
mixed_precision: ['fp16', 'bf16']
output_dir: './'
max_num_frames: 32
train_batch_size: 1
max_train_steps: 1000
checkpointing_steps: 400
gradient_accumulation_steps: 4
gradient_checkpointing: true
learning_rate: 0.0001
lr_scheduler: 'cosine_with_restarts'
lr_warmup_steps: 400
lr_num_cycles: 1
enable_slicing: true
enable_tiling: true
optimizer: 'adamw'
beta1: 0.9
beta2: 0.95
weight_decay: 0.001
max_grad_norm: 1.0
allow_tf32: true
nccl_timeout: 1800
resume_from_checkpoint: ''


