batch_size: 1
caption_column: prompt.txt
data_root: ./
dtype: fp16
frame_buckets: 32 48
height_buckets: 384 480
max_num_frames: 48
max_sequence_length: 226
model_id: ' '
nproc_per_node: 1
output_dir: ' '
save_image_latents: false
save_latents_and_embeddings: false
target_fps: 8
video_column: videos.txt
width_buckets: 560 720
