train_accelerate_config: uncompiled_1.yaml
train_allow_tf32: true
train_beta1: 0.9
train_beta2: 0.95
train_caption_column: prompt.txt
train_checkpointing_steps: 500
train_data_root: ''
train_dataloader_num_workers: 6
train_enable_slicing: true
train_enable_tiling: true
train_frame_buckets: 49
train_gpu_ids: '0'
train_gradient_accumulation_steps: 4
train_gradient_checkpointing: true
train_height_buckets: 480
train_id_token: LORA_NAME
train_learning_rate: 0.0001
train_lora_alpha: 128
train_lr_num_cycles: 1
train_lr_scheduler: cosine_with_restarts
train_lr_warmup_steps: 400
train_max_grad_norm: 1.0
train_max_num_frames: 49
train_max_train_steps: 3000
train_mixed_precision: fp16
train_nccl_timeout: 1800
train_num_validation_videos: 0
train_optimizer: adamw
train_output_dir: ./
train_pin_memory: true
train_pretrained_model_name_or_path: ''
train_rank: 128
train_resume_from_checkpoint: ''
train_seed: 42
train_train_batch_size: 1
train_training_type: cogvideox_text_to_video_sft
#train_use_learned_positional_embeddings: true
train_validation_epochs: 0
train_validation_prompt: ''
train_validation_prompt_separator: ':::'
train_video_column: videos.txt
train_weight_decay: 0.001
train_width_buckets: 720
